INSERT IGNORE INTO campo_crf (id_campo, activo, descripcion, nombre, pregunta_formulario, seccion, tipo) VALUES
(1, 1, NULL, 'edad', 'Edad:', 2, 'NUMERO'),
(2, 1, NULL, 'sexo', 'Sexo:', 2, 'SELECCION_UNICA'),
(3, 1, NULL, 'nacionalidad', 'Nacionalidad:', 2, 'TEXTO'),
(4, 1, NULL, 'zona', 'Zona', 2, 'SELECCION_UNICA'),
(5, 1, NULL, 'vive_mas_5_anios', '¿Vive usted en esta zona desde hace más de 5 años?', 2, 'SI/NO'),
(6, 1, NULL, 'nivel_educacional', 'Nivel educacional:', 2, 'SELECCION_UNICA'),
(7, 1, NULL, 'ocupacion_actual', 'Ocupación actual:', 2, 'TEXTO'),
(8, 1, NULL, 'prevision_salud', 'Previsión de salud actual', 2, 'SELECCION_UNICA'),
(9, 1, 'Ignorar este campo si no corresponde.', 'otra_prevision_salud', 'Si seleccionó "Otra", especifique:', 2, 'TEXTO'),
(10, 1, 'Ignorar este campo si no pertenece.', 'adenocarcinoma_gastrico', 'Diagnóstico histológico de adenocarcinoma gástrico (SOLO CASOS):', 3, 'SI/NO'),
(11, 1, 'Ignorar este campo si no pertenece.', 'fecha_diagnostico_adenocarcinoma', 'Fecha de diagnóstico (SOLO CASOS):', 3, 'FECHA'),
(12, 1, NULL, 'antecedentes_familiares', 'Antecedentes familiares de cáncer gástrico:', 3, 'SI/NO'),
(13, 1, NULL, 'antecedentes_familiares_otros', 'Antecedentes familiares de otros tipos de cáncer:', 3, 'SI/NO'),
(14, 1, 'Ignorar este campo si no corresponde.', 'antecedentes_familiares_otros_cual', 'Si la respuesta anterior fue "Sí", especifique cual:', 3, 'TEXTO'),
(15, 1, NULL, 'otras_enfermedades_relevantes', 'Otras enfermedades relevantes (ej. gastritis crónica, úlcera, diabetes):', 3, 'TEXTO'),
(16, 1, NULL, 'uso_medicamentos_gastrolesivos', 'Uso crónico de medicamentos gastrolesivos (AINES u otros):', 3, 'SI/NO'),
(17, 1, 'Ignorar este campo si no corresponde.', 'uso_medicamentos_gastrolesivos_cuales', 'Si la respuesta anterior fue "Sí", especifique cuales:', 3, 'TEXTO'),
(18, 1, NULL, 'cirugia_gastrica_previa', 'Cirugía gástrica previa (gastrectomía parcial):', 3, 'SI/NO'),
(19, 1, NULL, 'peso', 'Peso (kg):', 4, 'NUMERO'),
(20, 1, NULL, 'estatura', 'Estatura (m):', 4, 'NUMERO'),
(21, 1, NULL, 'imc', 'Índice de masa corporal (IMC = peso/estatura²):', 4, 'NUMERO'),
(22, 1, NULL, 'estado_tabaquismo', 'Estado de tabaquismo:', 5, 'SELECCION_UNICA'),
(23, 1, NULL, 'cantidad_promedio_fumada', 'Cantidad promedio fumada:', 5, 'SELECCION_UNICA'),
(24, 1, NULL, 'tiempo_total_fumando', 'Tiempo total fumando:', 5, 'SELECCION_UNICA'),
(25, 1, 'Ignorar este campo si no corresponde.', 'tiempo_sin_fumar', '(EXFUMADOR) - Tiempo desde que dejó de fumar:', 5, 'SELECCION_UNICA'),
(26, 1, NULL, 'estado_consumo', 'Estado de consumo:', 6, 'SELECCION_UNICA'),
(27, 1, NULL, 'frecuencia_consumo', 'Frecuencia:', 6, 'SELECCION_UNICA'),
(28, 1, NULL, 'cantidad_tipica', 'Cantidad típica por ocasión:', 6, 'SELECCION_UNICA'),
(29, 1, NULL, 'anios_consumo_habitual', 'Años de consumo habitual:', 6, 'SELECCION_UNICA'),
(30, 1, NULL, 'tiempo_sin_consumir', '(EXCONSUMIDOR) - Tiempo desde que dejó de beber regularmente:', 6, 'SELECCION_UNICA'),
(31, 1, NULL, 'consumo_carnes_procesadas', 'Consumo de carnes procesadas/cecinas:', 7, 'SELECCION_UNICA'),
(32, 1, NULL, 'consumo_alimentos_salados', 'Consumo de alimentos muy salados (agrega sal a la comida antes de probarla):', 7, 'SI/NO'),
(33, 1, NULL, 'consumo_frutas_verduras', 'Consumo de porciones de frutas y verduras frescas:', 7, 'SELECCION_UNICA'),
(34, 1, NULL, 'consumo_frecuente_frituras', 'Consumo frecuente de frituras (≥3 veces por semana):', 7, 'SI/NO'),
(35, 1, NULL, 'consumo_alimentos_condimentados', 'Consumo de alimentos muy condimentados (ají, salsas picantes):', 7, 'SELECCION_UNICA'),
(36, 1, NULL, 'consumo_bebidas_calientes', 'Consumo de infusiones o bebidas muy calientes (toma inmediatamente al servir):', 7, 'SELECCION_UNICA'),
(37, 1, NULL, 'exposicion_pesticidas', 'Exposición ocupacional a pesticidas:', 7, 'SI/NO'),
(38, 1, NULL, 'exposicion_otros_quimicos', 'Exposición a otros compuestos químicos:', 7, 'SI/NO'),
(39, 1, 'Ignorar este campo si no corresponde.', 'exposicion_otros_quimicos_cuales', 'Si la respuesta anterior fue "Sí", especifique cuales:', 7, 'TEXTO'),
(40, 1, NULL, 'humo_lenia_hogar', 'Humo de leña en el hogar (cocina/calefacción):', 7, 'SELECCION_UNICA'),
(41, 1, NULL, 'fuente_principal_agua', 'Fuente principal de agua en el hogar:', 7, 'SELECCION_UNICA'),
(42, 1, 'Ignorar este campo si no corresponde.', 'fuente_principal_agua_otra', 'Si seleccionó "Otra", especifique:', 7, 'TEXTO'),
(43, 1, NULL, 'tratamiento_agua_casa', 'Tratamiento del agua en casa:', 7, 'SELECCION_UNICA'),
(44, 1, 'IMPORTANTE: Si responde positivo, continuar directamente a la pregunta de tratamiento.', 'helicobacter_pylori', 'Resultado del examen para Helicobacter pylori:', 8, 'SELECCION_UNICA'),
(45, 1, '(IMPORTANTE: Si responde “Sí”, indicar año aproximado y tipo de examen).', 'h_pylori_positivo_pasado', '(RESULTADO NEGATIVO O DESCONOCIDO) - ¿Ha tenido alguna vez un examen positivo?', 8, 'SELECCION_UNICA'),
(46, 1, 'Ignorar este campo si no corresponde.', 'h_pylori_positivo_pasado_anio', 'Año aproximado:', 8, 'NUMERO'),
(47, 1, 'Ignorar este campo si no corresponde.', 'h_pylori_positivo_pasado_tipo', 'Tipo de examen:', 8, 'TEXTO'),
(48, 1, '(IMPORTANTE: Si responde “Sí”, indicar año aproximado y esquema).', 'h_pylori_tratamiento_pasado', '(RESULTADO NEGATIVO O DESCONOCIDO) - ¿Recibió tratamiento de erradicación?', 8, 'SELECCION_UNICA'),
(49, 1, 'Ignorar este campo si no corresponde.', 'h_pylori_tratamiento_pasado_anio', 'Año aproximado:', 8, 'NUMERO'),
(50, 1, 'Ignorar este campo si no corresponde.', 'h_pylori_tratamiento_pasado_esquema', 'Indicar esquema, si se conoce:', 8, 'TEXTO'),
(51, 1, NULL, 'tipo_examen', 'Tipo de examen realizado:', 8, 'SELECCION_UNICA'),
(52, 1, 'Ignorar este campo si no corresponde.', 'tipo_examen_otro', 'Si seleccionó "Otro", especifique:', 8, 'TEXTO'),
(53, 1, NULL, 'hace_cuanto_test', '¿Hace cuánto tiempo se realizó el test?:', 8, 'SELECCION_UNICA'),
(54, 1, NULL, 'uso_antibioticos_4_sem_previas', 'Uso de antibióticos o inhibidores de bomba de protones en 4 semanas previas:', 8, 'SELECCION_UNICA'),
(55, 1, '(IMPORTANTE: Si responde “Sí”, anotar fecha y resultado más reciente).', 'repetido_examen_anteriormente', '¿Ha repetido el examen posteriormente?', 8, 'SI/NO'),
(56, 1, 'Ignorar este campo si no corresponde.', 'repetido_examen_anteriormente_fecha', 'Indicar fecha:', 8, 'FECHA'),
(57, 1, 'Ignorar este campo si no corresponde.', 'repetido_examen_anteriormente_resultado', 'Resultado examen posterior más reciente:', 8, 'SELECCION_UNICA'),
(58, 1, NULL, 'tipo_histologico', '(SOLO CASOS) - Tipo histológico:', 9, 'SELECCION_UNICA'),
(59, 1, 'Ignorar este campo si no corresponde.', 'tipo_histologico_otro', 'Si seleccionó "Otro", especifique:', 9, 'TEXTO'),
(60, 1, NULL, 'localizacion_tumoral', '(SOLO CASOS) - Localización tumoral:', 9, 'SELECCION_UNICA'),
(61, 1, NULL, 'estado_clinico', '(SOLO CASOS) - Estadio clínico (TNM):', 9, 'TEXTO');


INSERT IGNORE INTO opcion_campo_crf (id_opcion, etiqueta, orden, id_campo) VALUES
(1, 'Hombre', 0, 2),
(2, 'Mujer', 1, 2),
(3, 'Urbana', 0, 4),
(4, 'Rural', 1, 4),
(5, 'Básico', 0, 6),
(6, 'Medio', 1, 6),
(7, 'Superior', 2, 6),
(8, 'Fonasa', 0, 8),
(9, 'Isapre', 1, 8),
(10, 'Capredena / Dipreca', 2, 8),
(11, 'Sin previsión', 3, 8),
(12, 'Otra', 4, 8),
(13, 'Nunca fumó (menos de 100 cigarrillos en la vida)', 0, 22),
(14, 'Exfumador', 1, 22),
(15, 'Fumador actual', 2, 22),
(16, '1–9 cigarrillos/día (poco)', 0, 23),
(17, '10–19 cigarrillos/día (moderado)', 1, 23),
(18, '≥20 cigarrillos/día (mucho)', 2, 23),
(19, '<10 años', 0, 24),
(20, '10–20 años', 1, 24),
(21, '>20 años', 2, 24),
(22, '<5 años', 0, 25),
(23, '5–10 años', 1, 25),
(24, '>10 años', 2, 25),
(25, 'Nunca', 0, 26),
(26, 'Exconsumidor', 1, 26),
(27, 'Consumidor actual', 2, 26),
(28, 'Ocasional (menos de 1 vez/semana)', 0, 27),
(29, 'Regular (1–3 veces/semana)', 1, 27),
(30, 'Frecuente (≥4 veces/semana)', 2, 27),
(31, '1–2 tragos (poco)', 0, 28),
(32, '3–4 tragos (moderado)', 1, 28),
(33, '≥5 tragos (mucho)', 2, 28),
(34, '<10 años', 0, 29),
(35, '10–20 años', 1, 29),
(36, '>20 años', 2, 29),
(37, '<5 años', 0, 30),
(38, '5–10 años', 1, 30),
(39, '>10 años', 2, 30),
(40, '≤1/sem', 0, 31),
(41, '2/sem', 1, 31),
(42, '≥3/sem', 2, 31),
(43, '≥5 porciones/día (adecuado/protector)', 0, 33),
(44, '3–4 porciones/día (intermedio)', 1, 33),
(45, '≤2 porciones/día (bajo/insuficiente, riesgo)', 2, 33),
(46, 'Casi nunca / Rara vez', 0, 35),
(47, '1 a 2 veces por semana', 1, 35),
(48, '3 o más veces por semana', 2, 35),
(49, 'Nunca/Rara vez', 0, 36),
(50, '1–2/sem', 1, 36),
(51, '≥3/sem', 2, 36),
(52, 'Nunca/Rara vez', 0, 40),
(53, 'Estacional', 1, 40),
(54, 'Diario', 2, 40),
(55, 'Red pública', 0, 41),
(56, 'Pozo', 1, 41),
(57, 'Camión aljibe', 2, 41),
(58, 'Otra', 3, 41),
(59, 'Ninguno', 0, 43),
(60, 'Hervir', 1, 43),
(61, 'Filtro', 2, 43),
(62, 'Cloro', 3, 43),
(63, 'Positivo', 0, 44),
(64, 'Negativo', 1, 44),
(65, 'Desconocido', 2, 44),
(66, 'Sí', 0, 45),
(67, 'No', 1, 45),
(68, 'No recuerda', 2, 45),
(69, 'Sí', 0, 48),
(70, 'No', 1, 48),
(71, 'No recuerda', 2, 48),
(72, 'Test de aliento (urea-C13/C14)', 0, 51),
(73, 'Antígeno en deposiciones', 1, 51),
(74, 'Serología (IgG)', 2, 51),
(75, 'Test rápido de ureasa', 3, 51),
(76, 'Histología / Biopsia', 4, 51),
(77, 'Otro', 5, 51),
(78, '<1 año', 0, 53),
(79, '1–5 años', 1, 53),
(80, '>5 años', 2, 53),
(81, 'Sí', 0, 54),
(82, 'No', 1, 54),
(83, 'No recuerda', 2, 54),
(84, 'Positivo', 0, 57),
(85, 'Negativo', 1, 57),
(86, 'Intestinal', 0, 58),
(87, 'Difuso', 1, 58),
(88, 'Mixto', 2, 58),
(89, 'Otro', 3, 58),
(90, 'Cardias', 0, 60),
(91, 'Cuerpo', 1, 60),
(92, 'Antro', 2, 60),
(93, 'Difuso', 3, 60);